name: stogo_play
description: "A new Flutter project."
publish_to: 'none' # Do not remove this lineâŒ.

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter


  get: 
  just_audio:
  cupertino_icons: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/audio/
    - assets/images/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400